EMBCESSMOD-1897: Wizard Step Service & Cleanup
bcgov/embc-ess-mod pull request #469
Opened 2021-07-02 22:32 UTC by MShayOffice

Set up WizardStepService, with functions for existing wizard entry points, and placeholders for some upcoming ones.
Standardized some naming conventions, updated some values to match current API configuration, renamed some methods for clarity.
Mapping for getProfileFromId and getFileFromId has more accurate type descriptions, consolidated their `Address > AddressModel` conversion code into LocationsService. Can move this somewhere else if preferred.

Noteworthy functions:
- `evacueeProfileStepFromSearch` sets up the pre-set Personal Details values **during the Activation Guard** for the Create Profile step, if entered from the Search page
- `stepEvacueeProfileService.setFormValuesFromProfile` fills in the Evacuee Profile step with profile data **immediately after creating profile** and can also be used when loading Edit wizard. Also sets Profile ID.
- `essFileStepFromProfileCreation` sets up the Profile ID (in evacueeSession), PrimaryAddress, and PrimaryMember **after clicking "Proceed to Step 2"**
- `stepEssFileService.setFormValuesFromFile` fills in the ESS File step with file data **immediately after creating file** and can also be used when loading Edit wizard. Also sets ESS File Number.
- `getAddressModelFromAddress` uses the location lists to fetch address objects and change an Address object to an AddressModel object, combining 3 large blocks of code from the "Get profile/file" services into 1 reusable function.

2021-07-03 00:00 UTC, SodhiA1 requested changes

2021-07-03 00:01 UTC, SodhiA1 commented
Rest of the changes look good. Task Number change is critical

2021-07-05 15:58 UTC, MShayOffice commented on responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
> +    this.cacheService.remove('taskNumber');
Good catch - I briefly considered having a copy of the task number in evacuee session, and forgot to remove this line after I decided against it.

2021-07-05 16:06 UTC, MShayOffice commented on responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-activate.guard.ts
> +        if (wizardFromPage === '/responder-access/search/evacuee') {
Will do. If there's ever a case where the same wizard can be entered from multiple sources, we can still use this method or something similar to figure out which step-setup function to use.

2021-07-05 16:29 UTC, SodhiA1 approved these changes

2021-07-05 16:30 UTC, merged